CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    Department NVARCHAR(50),
    Salary DECIMAL(10, 2)
);
INSERT INTO Employees (EmployeeID, FirstName, LastName, Department, Salary) VALUES
(1, 'John', 'Doe', 'Sales', 50000.00),
(2, 'Jane', 'Smith', 'HR', 60000.00),
(3, 'Mike', 'Brown', 'IT', 70000.00),
(4, 'Anna', 'Taylor', 'Sales', 55000.00);

--BELOW CURSOR TO ITERATE THROUGH EACH EMPLOYEE AND GIVE A 10% RAISE TO THOSE IN THE SALES DEPARTMENT.

-- DECLARE VARIABLES TO HOLD CURSOR DATA
DECLARE @EMPLOYEEID INT, @FIRSTNAME NVARCHAR(50), @LASTNAME NVARCHAR(50), @DEPARTMENT NVARCHAR(50), @SALARY DECIMAL(10, 2);
-- DECLARE THE CURSOR
DECLARE EMPLOYEECURSOR CURSOR FOR
SELECT EMPLOYEEID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY
FROM EMPLOYEES;
-- OPEN THE CURSOR
OPEN EMPLOYEECURSOR;
-- FETCH THE FIRST ROW FROM THE CURSOR
FETCH NEXT FROM EMPLOYEECURSOR INTO @EMPLOYEEID, @FIRSTNAME, @LASTNAME, @DEPARTMENT, @SALARY;
-- LOOP THROUGH THE ROWS
WHILE @@FETCH_STATUS = 0
BEGIN
    -- CHECK IF THE DEPARTMENT IS SALES
    IF @DEPARTMENT = 'SALES'
    BEGIN
        -- UPDATE THE SALARY WITH A 10% RAISE
        UPDATE EMPLOYEES
        SET SALARY = @SALARY * 1.10
        WHERE CURRENT OF EMPLOYEECURSOR;
    END
    -- FETCH THE NEXT ROW FROM THE CURSOR
    FETCH NEXT FROM EMPLOYEECURSOR INTO @EMPLOYEEID, @FIRSTNAME, @LASTNAME, @DEPARTMENT, @SALARY;
END
-- CLOSE AND DEALLOCATE THE CURSOR
CLOSE EMPLOYEECURSOR;
DEALLOCATE EMPLOYEECURSOR;
